import type { SunEditor } from "suneditor/types";

export const FullButtonList: SunEditor.UI.ButtonList = [
	// full size
	["undo", "redo", "|", "dir", "newDocument", "selectAll", "save", "preview", "print", "exportPDF"],
	"|",
	["blockquote", "|", "blockStyle", "font", "fontSize", "|", "paragraphStyle", "textStyle"],
	"|",
	["bold", "underline", "italic", "strike", "subscript", "superscript"],
	["fontColor", "backgroundColor"],
	"|",
	["removeFormat", "copyFormat"],
	"|",
	["table", "lineHeight"],
	"/",
	["align", "list_numbered", "list_bulleted"],
	"|",
	["outdent", "indent"],
	"|",
	["hr", "link", "anchor", "math"],
	"|",
	["image", "drawing", "video", "audio", "embed", "fileUpload"],
	"|",
	["imageGallery", "videoGallery", "audioGallery", "fileGallery", "fileBrowser"],
	"|",
	["template", "layout"],
	"|",
	["fullScreen", "showBlocks", "codeView"],
	"|",
	["pageBreak", "pageNavigator", "pageUp", "pageDown"],
	"|",
	["copy"],
	// (min-width: 1200)
	[
		"%1200",
		[
			["undo", "redo", "|", "dir", "newDocument", "selectAll", "save", "preview", "print", "exportPDF"],
			"|",
			[":Paragraph-default.more_paragraph", "blockquote", "|", "blockStyle", "font", "fontSize", "|", "paragraphStyle"],
			"|",
			["textStyle"],
			["bold", "underline", "italic", "strike", "subscript", "superscript"],
			["fontColor", "backgroundColor"],
			"|",
			["removeFormat", "copyFormat"],
			"/",
			["outdent", "indent"],
			"|",
			[":Lists & Align-default.more_list", "table", "lineHeight", "align", "list_numbered", "list_bulleted"],
			[":Media & File-default.more_media", "image", "drawing", "video", "audio", "embed", "fileUpload"],
			[":Galleries-default.more_gallery", "imageGallery", "videoGallery", "audioGallery", "fileGallery", "fileBrowser"],
			"|",
			["hr", "link", "anchor", "math"],
			"|",
			["template", "layout"],
			"|",
			["fullScreen", "showBlocks", "codeView"],
			"|",
			["pageBreak", "pageNavigator", "pageUp", "pageDown"],
			"|",
			["copy"],
		],
	],
	// (min-width: 992)
	[
		"%992",
		[
			["undo", "redo", "|", "dir", "newDocument", "selectAll", "save", "preview", "print", "exportPDF"],
			"|",
			[":Paragraph-default.more_paragraph", "blockquote", "|", "blockStyle", "font", "fontSize", "|", "paragraphStyle"],
			"|",
			[":Text-default.more_text", "bold", "underline", "italic", "strike", "subscript", "superscript", "fontColor", "backgroundColor", "|", "removeFormat", "copyFormat", "textStyle", "copy"],
			["outdent", "indent"],
			"|",
			[":Insert-default.more_plus", "hr", "link", "anchor", "math"],
			"|",
			[":Lists & Align-default.more_list", "table", "lineHeight", "align", "list_numbered", "list_bulleted"],
			[":Media & File-default.more_media", "image", "drawing", "video", "audio", "embed", "fileUpload"],
			[":Galleries-default.more_gallery", "imageGallery", "videoGallery", "audioGallery", "fileGallery", "fileBrowser"],
			[":Templates-default.more_file", "template", "layout"],
			["-right", ":View-default.more_view", "preview", "print", "fullScreen", "showBlocks", "codeView"],
		],
	],
	// (min-width: 768)
	[
		"%768",
		[
			["undo", "redo"],
			"|",
			[":Docs-default.more_horizontal", "dir", "newDocument", "selectAll"],
			["save"],
			[":Paragraph-default.more_paragraph", "blockquote", "|", "blockStyle", "font", "fontSize", "|", "paragraphStyle"],
			[":Text-default.more_text", "bold", "underline", "italic", "strike", "subscript", "superscript", "fontColor", "backgroundColor", "|", "removeFormat", "copyFormat", "textStyle", "copy"],
			["outdent", "indent"],
			[":Insert-default.more_plus", "hr", "link", "anchor", "math"],
			"|",
			[":Lists & Align-default.more_list", "table", "lineHeight", "align", "list_numbered", "list_bulleted"],
			[":Media & File-default.more_media", "image", "drawing", "video", "audio", "embed", "fileUpload"],
			[":Galleries-default.more_gallery", "imageGallery", "videoGallery", "audioGallery", "fileGallery", "fileBrowser"],
			[":Templates-default.more_file", "template", "layout"],
			"|",
			["-right", ":Pages-default.more_page", "pageBreak", "pageNavigator", "pageUp", "pageDown"],
			["-right", ":View-default.more_view", "preview", "print", "exportPDF", "fullScreen", "showBlocks", "codeView"],
		],
	],
	// (min-width: 525)
	[
		"%576",
		[
			["undo", "redo"],
			"|",
			[":Docs-default.more_horizontal", "dir", "newDocument", "selectAll", "save"],
			[":Paragraph-default.more_paragraph", "outdent", "indent", "|", "blockquote", "|", "blockStyle", "font", "fontSize", "|", "paragraphStyle"],
			[":Text-default.more_text", "bold", "underline", "italic", "strike", "subscript", "superscript", "fontColor", "backgroundColor", "|", "removeFormat", "copyFormat", "textStyle", "copy"],
			[":Insert-default.more_plus", "hr", "link", "anchor", "math"],
			[":Lists & Align-default.more_list", "table", "lineHeight", "align", "list_numbered", "list_bulleted"],
			[":Media & File-default.more_media", "image", "drawing", "video", "audio", "embed", "fileUpload"],
			[":Galleries & Templates-default.more_gallery", "imageGallery", "videoGallery", "audioGallery", "fileGallery", "fileBrowser", "|", "template", "layout"],
			[":View & Pages-default.more_view", "preview", "print", "exportPDF", "fullScreen", "showBlocks", "codeView", "|", "pageBreak", "pageNavigator", "pageUp", "pageDown"],
		],
	],
];
